 version: "3"
 services:
    api: 
        build: .
        depends_on:
            - postgres
        ports: [8000:8000]
        volumes: [./:/usr/src/app:ro]
        env_file:
            - ./.env
        environment:
            - DATABASE_HOSTNAME= # include host name here
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD= # include password here
            - DATABASE_NAME= # include name here
            - DATABASE_USERNAME=postgres
            - SECRET_KEY= # secret key here
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=30        
 postgres: 
    image: postgres
    environment:
        - POSTGRES_PASSWORD= # password here
        - POSTGRES_DB=fastapi
    
    volumes:
        - postgres-db:/var/lib/postgresql/data

 volumes:
     postgres-db: